theme: jekyll-theme-minimal

title: Shai Caspin
description: Student at University of North Carolina at Chapel Hill studying Computer Science and Applies Mathematics
logo: pictures/Caspin_Headshot.png
